namespace: ansible
name: kubernetes
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible.misc: '>=1.0'
  ansible.windows: '>=1.0'
  ansible.unix: '>=1.0'
repository: git@github.com:coll-test/ansible.kubernetes.git
documentation: https://github.com/coll-test/ansible.kubernetes/tree/master/docs
homepage: https://github.com/coll-test/ansible.kubernetes
issues: https://github.com/coll-test/ansible.kubernetes/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
